---
version: 2
mergeable:
  - when: pull_request.*, issues.*
    validate:
      - do: title
        no_empty:
          enabled: true
          message: 'Please add a title.'
        must_exclude:
          regex: ^\[WIP\]
      - do: label
        must_exclude:
          regex: 'WIP'
  - when: schedule.repository
    validate:
      - do: stale
        days: 5
        type: pull_request, issues
    pass:
      - do: comment
        payload:
          body: This is old. Is it still relevant?
